# -*- coding: utf-8 -*-
"""rock_paper_s

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8fhPhEtyDsPYzMGoHOJq0qfYvB86QlL

# Rock, Paper, Scissors Game:

This Python script is a simple Rock, Paper, Scissors game where the user plays against the computer.

1. Importing the Random Module
"""

import random

"""* The random module is used to let the computer randomly pick rock ('r'), paper ('p'), or scissors ('s').

2. play() Function: Running the Game
"""

def play():
    user = input("What's your choice? 'r' for rock, 'p' for paper, 's' for scissors: ").lower()
    computer = random.choice(['r', 'p', 's'])

    print(f"Computer chose: {computer}")

    if user == computer:
        return "It's a tie!"

"""How It Works:

* The user enters 'r' for rock, 'p' for paper, or 's' for scissors.

* The computer randomly selects one of the three choices.

* The user's and computer's choices are compared:

* If both choices are the same, it's a tie.

3. Determining the Winner
"""

# r > s, s > p, p > r
    if is_win(user, computer):
        return "You won!"

    return "You lost!"

"""How It Works:

* The function calls is_win(user, computer) to check if the user wins.

* If is_win(user, computer) returns True, the user wins.
Otherwise, the user loses.

4. is_win() Function: Checking Win Conditions
"""

def is_win(player, opponent):
    # Returns True if player wins
    # r > s, s > p, p > r
    return (player == 'r' and opponent == 's') or \
           (player == 's' and opponent == 'p') or \
           (player == 'p' and opponent == 'r')

"""How It Works:

* The function checks whether the player's choice beats the opponent's choice.

The rules of the game:

* Rock ('r') beats Scissors ('s')

* Scissors ('s') beats Paper ('p')

* Paper ('p') beats Rock ('r')

* If the player wins based on these rules, the function returns True.

5. Running the Game
"""

# Run the game
print(play())

"""* Calls the play() function to start the game.

* Prints the result (win, lose, or tie).
"""